defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

avatar: "assets/images/ofx_800.png"
title:
#subtitle: Full-Stack Developer

left_side:
   background_image: ""
   background_color: "#f2f9fe"
#   close_button_color: "#F00"
   text_color: "#959595"

footer:
  copyright_text: "&copy; Unkoder"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Tutorial
    link: /tutorial
    icon: ""
    
  - text: News
    link: /news
    icon: ""

  - text: Downloads
    link: /downloads
    icon: ""

  

# Socialmedia Icons
social_icons:
  - name: twitter
    link: https://www.twitter.com/OF_Xtractor
    icon: fab fa-twitter
    
  - name: facebook
    link: mailto:unkoder.dev@gmail.com
    icon: fab fa-mail

# Google Analytics
google_analytics: UA-177506252-1

    
