defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

avatar: "assets/images/ofx_800.png"
title:
#subtitle: Full-Stack Developer

left_side:
   background_image: ""
   background_color: "#f2f9fe"
#   close_button_color: "#F00"
   text_color: "#959595"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Tutorial
    link: /tutorial
    icon: ""
    
  - text: News
    link: /news
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
